### ISSUE TITLE
Update images with Graph view in it

### ISSUE THREAD

**Issue by Surendrajat** [rizinorg/cutter.re#19]
**Describe the issue**
Below two images are outdated now as the graph view has been improved in https://github.com/radareorg/cutter/commit/54ecc33ca96fab43cf11c0a8ec3906b77bcc29f0

![cutter_head_light_theme.png](https://github.com/radareorg/cutter.re/raw/master/assets/images/cutter_head_light_theme.png)
![graph_overview.png](https://github.com/radareorg/cutter.re/raw/master/assets/images/graph_overview.png)

**How to reproduce?**
Visit https://cutter.re

**Expected behavior**
We can show a better SS here.

**Possible fix**
Need to open cutter in light theme(dangerous) and SS it.

**Screenshots**
Above

**Additional context**

**Comment by XVilka** [comment]
Probably better to coincide with the Cutter 2.0 release cc @thestr4ng3r @karliss @ITAYC0HEN

**Comment by XVilka** [comment]
@Surendrajat could you  please send a PR?
