### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by jgollenz** [rizinorg/cutter.re#44]
[here](https://github.com/rizinorg/cutter.re/blob/8069603d608bb7ff369611177f6a28eba0608cdc/_includes/highlights.html#L9)

I assume the intention is `Cutters goal`, not `Cutter goal`.

**Comment by ITAYC0HEN** [comment]
Right :) Thank you very much for noticing and notifying us.
Would you like to try and send a Pull Request with this change? :)
